language: node_js
cache: npm
git:
  depth: 3

env:
  global:
    - COVERALLS_PARALLEL=true

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test:cover
      notifications:
        webhooks: https://coveralls.io/webhook

deploy:
  provider: lambda
  region: us-west-1
  runtime: nodejs12.x
  function_name: deploy-lambda-travis
  handler_name: hello
  role: arn:aws:iam::673233482676:role/service-role/lambda_basic_execution
  on:
    branch: main
