language: node_js
cache: npm
git:
  depth: 3

stages:
  - lint
  - test
  - name: deploy
    if: branch = main
jobs:
  include:
    - name: Lint code
      stage: lint
      script: npm run lint
    - name: Run tests
      stage: test
      script: npm run test:cover
      after_success: npm run coveralls
    - name: Deploy to AWS Lambda
      stage: deploy
      script: skip
      deploy: &lambda
        provider: lambda
        region: us-west-1
        runtime: nodejs12.x
        function_name: deploy-lambda-travis
        handler_name: hello
        role: arn:aws:iam::673233482676:role/service-role/lambda_basic_execution
        on:
          branch: main

notifications:
  email: false
  slack:
    if: branch = master
    rooms:
      # eslint-disable-next-line max-len
      - secure: "tbDbyikANQl1NCUleZ0OqblMChCNOnTSby+gIE1A5FLytkJV3FqQK8nEHSLVt+d1qHoLMy8/WPCqh+nC5NgHG+vaEaO/mdTif1RjkzIiBIxjUhiH5m9oww/wFIQmn3SuyX9vBoP1E5aFdkIghm7Q3gQDceSZrxokVusR2xWeHwxmIS+aJyW2AMfVGN+lhDXhfSqGf48nkegveowc40KqVXNyxnUA9z2lSX9Y4TP204AbnBFFVAVuY/JuOPZNVRLjIo9RljFeFtQOWa1B/Ao4RPT4OEdolnwOmR8n7unpQglN4DpB4XisWLoEeo95x6D/oSoUOldZMy2dOvfcq3aPG6Kd5T5K+mnve07x2rJ64OcGh7+jQJxXLLHEwLhLddyEjwWsKXowHuCEVaBi9yBVuFVEsQkNR+bnhdEp3xptmOczp6hUFyq7JDFRaJlCSsertfKcQ/SXDUBjyU22OqNUMwD6bNl+FrnFe/M2s4wwuiLCr5zd+3KwDeU5mVjAj8H54Ll4ixE2Z2c9avZRlEEmuHCwBP9HAT4XhiVNNh6+vS0/i6pX9N6Zfe19cMSBhE8lJ2Frgt7lrX0Iwu9nBxvBp/RVu87OCqLMcAnAcdt8J+v88ajAlsMxBCd3yAUs0OrrzHAk7UxR4HpHQGpatDIWHa+Poy54oKebKTBN+7lStRc="
