language: node_js
cache: npm
git:
  depth: 3

stages:
  - lint
  - test

jobs:
  include:
    - name: Lint code
      stage: lint
      script: npm run lint
    - name: Run tests
      stage: test
      script: npm run coveralls
# deploy:
#   provider: lambda
#   region: us-west-1
#   runtime: nodejs12.x
#   function_name: deploy-lambda-travis
#   handler_name: hello
#   role: arn:aws:iam::673233482676:role/service-role/lambda_basic_execution
#   on:
#     branch: main
